### ISSUE TITLE
[進捗管理]試験仕様書で行追加されると管理表のindirect関数がずれる

### ISSUE THREAD

**Issue by suzuki-maruchan** [suzuki-maruchan/workTask#7]
### ソリューション
どーしよ、、、アプローチとしては下記1点のみ？
**各試験仕様書の進捗表のフォーマットを改善する**

**Comment by high-technician** [comment]
aggregateTableNameシートのB列のシート名を使ってみたらどうだろう

**Comment by suzuki-maruchan** [comment]
`IF(INDIRECT(" & """" & "'" & """" & "&B" & (4 + i + count) & "&" & """" & "'!" & columnId & inputedexecutingDateCell.Row & """" & ")=0," & """" & "未打鍵" & """" & "," & "TEXT(INDIRECT(" & """" & "'" & """" & "&B" & (4 + i + count) & "&" & """" & "'!" & columnId & inputedexecutingDateCell.Row & """" & ")," & """" & "yyyy/mm/dd" & """" & "))"`
ここのINDIRECT部分を直接参照にすればよいとのこと

**Comment by suzuki-maruchan** [comment]
修正するンゴ！！

**Comment by suzuki-maruchan** [comment]
@high-technician 
テクニャン氏のご指摘通り修正しましたん！
試しに行を1行増やしてみた結果、ちゃんと対応して行番号がずれてました！
良い感じです^^

**Comment by suzuki-maruchan** [comment]
#29 のMergeで完了。クローズ。
